// this file is auto generated by Makefile/CMake
#define SLS_MAJOR 0
#define SLS_MINOR 3
#define SLS_PATCH 3

#define SLS_USE_SQLITECPP
#define SLS_USE_SQLITE
#define SLS_USE_UTFCPP

#define SLS_CHECK_BOUNDS
#define SLS_CHECK_SHAPES
#define NDEBUG
// #define SLS_USE_ASAN
